# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory to /app
WORKDIR /app/server

# Copy server package.json and package-lock.json files to the container
COPY server/package*.json ./

# Install server dependencies
RUN npm install
# Copy the server directory contents into the container
COPY server ./

# Set the working directory for the client
WORKDIR /app/client

# Copy client package.json and package-lock.json files to the container
COPY client/package*.json ./

# Install client dependencies
RUN npm install

# Copy the client directory contents into the container
COPY client ./

# Build the client
RUN npm run build

# Move build files to the server's public directory
RUN cp -r build ../server/public

# Set the working directory back to /app/server
WORKDIR /app/server

# Expose port 5000
EXPOSE 5000

# Start the server
CMD ["node", "index.js"]
