# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy server package.json and package-lock.json files to the container
COPY server/package*.json ./server/

# Copy client package.json and package-lock.json files to the container
COPY client/package*.json ./client/

# Install server dependencies
RUN cd ./server && npm install

# Install client dependencies
RUN cd ./client && npm install

# Copy the rest of the server and client directories into the container
COPY server ./server
COPY client ./client

# Build the client
RUN cd ./client && npm run build

# Move build files to the server's public directory
RUN cp -r ./client/build ./server/public

# Set the working directory back to /app/server
WORKDIR /app/server

# Expose port 5000
EXPOSE 5000

# Start the server
CMD ["node", "index.js"]
